# numpy
* https://numpy.org/learn/
* numpy: Nemerical Python 과학적, 산업적 연산을 위한 패키지 
* **다차원 배열, 행렬, 연산에 주로 사용**
* numpy는 pyhton의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이는 자료형이 1가지만 들어간다.
* 

# 차원
* 0차원 = 점,  스칼라 a= 10
* 1차원 = 선 ------ 벡터, 배열, list, tuple,[1,2,3,4]
  * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로 세로, DB 테이블, Dataframe, matrix
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체
* 4차원 = 3차원 요소가 2개 이상
* 5차원 = 4차원요소가 2개 이상

In [1]:
import numpy as np

In [20]:
# 1차원 데이터
a = np.array([1,2,3,4,5])

In [21]:
s = 10
# 스칼라

* 차원을 출력하는 메서드 .ndim,
* 차원의 형태를 출력하는 메서드 .shape

In [22]:
# ndim
a.ndim

1

In [23]:
# 방향이 없는 벡터
#(5, )로 표기되는 것은 그렇게 표기하고 있고 다른 방향이 있는 것을 표기하기 위한 것임,
# 방향이 없음의 표기
a.shape

(5,)

In [24]:
# 2차원 데이터
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [25]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
c.ndim

2

In [11]:
c.shape
# 앞에가 행, 뒤에가 열

(2, 5)

In [13]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [14]:
d.shape

(2, 2, 5)

In [16]:
# 4차원 데이터 
e = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [17]:
e.ndim

4

In [18]:
e.shape

(2, 2, 2, 5)

In [19]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]],[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [28]:
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
a2.shape

(5, 1)

# 넘파이를 사용하는 이유
* 행렬연산이 쉽고 빠르기 때문

In [30]:
# 스칼라 연산
a = 10
b = 5
scalar = a+ b
print(scalar)

15


In [31]:
scalar+ 10

25

In [32]:
# 1차원 데이터 백터의 연산
b1 = [1,2,3,4,5]
# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요.
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [33]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [35]:
# 2차원 데이터 계산 *10하기
second = np.array([[1,2,3],[1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [108]:
result = []
for num in second:
    mid_result = []
    for number in num:
        mid_result.append(number * 10)
    result.append(mid_result)
result = np.array(result)

In [109]:
result.ndim

2

In [110]:
result.shape

(2, 3)

In [37]:
# 3차원 데이터의 요소에 10곱하기
third = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [111]:
result = []
for num1 in third:
    num1_result = []
    for num2 in num1:
        num2_result = []
        for num3 in num2:
            num2_result.append(num3 * 10)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)

In [112]:
result.ndim

3

In [113]:
result

array([[[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [42]:
# 4차원 데이터에 10곱하기
forth = np.array([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]])

In [43]:
forth * 10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [47]:
# 5차원 데이터에 10 곱하기
fifth = np.array([[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]],[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [48]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# numpy 에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 보는 것
* .shape: 몇차원, 몇행, 몇열로 되어있는지 구조 확인
* .size: 배열안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

In [49]:
fifth.ndim

5

In [50]:
fifth.shape

(2, 2, 2, 2, 3)

In [51]:
fifth.size

48

In [54]:
fifth.dtype
# 'int64', 'int32', 'int16'등의 표현식으로 나눔. 표현식의 범위에 따라 자료의 범위가 다르고, 용량이 커지기 때문에 최적화를 잘 해줘야함
# 'float64' 소수도 표현 가능함

dtype('int64')

# ndarray 만들기
* numpy의 기본 자료형 ndarray(n차원(demention)배열(array))
* np.array(리스트/튜플)
* 자료형은 반드시 한가지 자료형으로만 만든다.

In [56]:
e = np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [55]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [58]:
e = np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [62]:
e2 = np.array([1,2,3.14,4,5])
print(e2)
e2.dtype

[1.   2.   3.14 4.   5.  ]


dtype('float64')

In [65]:
e3 = np.array([True,1,2,3,"4",5])
print(e3)
e3.dtype # 문자열 표기 

['True' '1' '2' '3' '4' '5']


dtype('<U21')

### 타입을 잘 넣어야 바뀌지 않는다.

* np.arange(시작,끝, step)

In [67]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [70]:
a2 = np.arange(11,1, -3)
a2

array([11,  8,  5,  2])

In [71]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [74]:
# .reshape(행,열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20, 5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [75]:
a5 = a3.reshape(5,4,5)
a5

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [ ]:
a6 = a3.reshape(25, )
print(a6.ndim)
print(a6.shape)

In [77]:
# fattren() : 다차원의 배열을 1차원으로 펼쳐줌
a5.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [79]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [80]:
a7.ndim

4

In [81]:
a7.shape

(3, 2, 2, 2)

In [83]:
a72 = a7.flatten()
a72

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
a73 = a72.reshape(3,2,2,2)
a73

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [85]:
a73.ndim

4

### np.flip() 행렬의 순서를 뒤집을 때


In [86]:
np.flip(a73)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [90]:
a73[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

## np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
* 반드시 시작과 끝은 입력수이다. 

In [91]:
# np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [92]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [93]:
np.linspace(1, 10, 539)

array([ 1.        ,  1.01672862,  1.03345725,  1.05018587,  1.0669145 ,
        1.08364312,  1.10037175,  1.11710037,  1.133829  ,  1.15055762,
        1.16728625,  1.18401487,  1.20074349,  1.21747212,  1.23420074,
        1.25092937,  1.26765799,  1.28438662,  1.30111524,  1.31784387,
        1.33457249,  1.35130112,  1.36802974,  1.38475836,  1.40148699,
        1.41821561,  1.43494424,  1.45167286,  1.46840149,  1.48513011,
        1.50185874,  1.51858736,  1.53531599,  1.55204461,  1.56877323,
        1.58550186,  1.60223048,  1.61895911,  1.63568773,  1.65241636,
        1.66914498,  1.68587361,  1.70260223,  1.71933086,  1.73605948,
        1.7527881 ,  1.76951673,  1.78624535,  1.80297398,  1.8197026 ,
        1.83643123,  1.85315985,  1.86988848,  1.8866171 ,  1.90334572,
        1.92007435,  1.93680297,  1.9535316 ,  1.97026022,  1.98698885,
        2.00371747,  2.0204461 ,  2.03717472,  2.05390335,  2.07063197,
        2.08736059,  2.10408922,  2.12081784,  2.13754647,  2.15

# 정렬, .sort(), sorted()
* 전체정렬

In [98]:
# 정렬, .sort(), sorted()
f = np.array([5,7,11,1,3,5,6,3,67,0,23,0.5])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  5. ,  6. ,  3. , 67. ,  0. , 23. ,
        0.5])

In [97]:
f.sort()

f

array([ 0. ,  0.5,  1. ,  3. ,  3. ,  5. ,  5. ,  6. ,  7. , 11. , 23. ,
       67. ])

In [ ]:
f.sort(order=True)

f

In [101]:
print(sorted(f, reverse=True))
f

[np.float64(67.0), np.float64(23.0), np.float64(11.0), np.float64(7.0), np.float64(6.0), np.float64(5.0), np.float64(5.0), np.float64(3.0), np.float64(3.0), np.float64(1.0), np.float64(0.5), np.float64(0.0)]


array([ 5. ,  7. , 11. ,  1. ,  3. ,  5. ,  6. ,  3. , 67. ,  0. , 23. ,
        0.5])

In [ ]:
f = np.array([5,7,11,1,3,5,6,3,67,0,23,0.5])
f

## argsort() 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
* 부분정렬

In [102]:
g = np.array([5,0.5,-7,42,10,0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [ ]:
# 2, 5, 1, 0, 4, 3

In [105]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [107]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

추천시스템 만들때, ex) 영화, 금융상품
* 정렬해줌